name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: pexcn/docker-images:buster-openwrt
      volumes:
        - /usr/local/lib/android:/usr/local/lib/android
        - /usr/share/dotnet:/usr/share/dotnet
        - /opt/ghc:/opt/ghc
        - /opt/hostedtoolcache/CodeQL:/opt/hostedtoolcache/CodeQL
    env:
      TZ: Asia/Taipei
      BUILD_PROFILE: ${{ matrix.PROFILE }}
    strategy:
      fail-fast: false
      matrix:
        PROFILE:
          - ipq60xx-generic
  
    steps:
      - name: Maximize build space
        run: |
          sudo find /usr/local/lib/android -mindepth 1 -delete
          sudo find /usr/share/dotnet -mindepth 1 -delete
          sudo find /opt/ghc -mindepth 1 -delete
          sudo find /opt/hostedtoolcache/CodeQL -mindepth 1 -delete

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build firmware
        run: ./build.sh

      - name: Upload to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_PROFILE }}
          path: openwrt/bin

      - name: Upload to Releases
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.BUILD_PROFILE }}.tar.gz
